#
# $Id: committer_opt_in.pm,v 1.1.2.16 2005-12-12 11:47:18 dan Exp $
#
# Copyright (c) 2001-2003 DVL Software
#

package FreshPorts::CommitterOptIn;

use email;
use config;
use strict;

use Text::Wrap;

$FreshPorts::CommitterOptIn::CommitMessageID      = '';
$FreshPorts::CommitterOptIn::CommitMessageSubject = '';
$FreshPorts::CommitterOptIn::Errors               = '';

my %PortList;

sub RecordErrorDetails {
	my $Port     = shift;
	my $ErrorMsg = shift;

	# we'll keep the error msg with the port name, in case we use it one day
	if (defined($PortList{$Port})) {
		$PortList{$Port} .= $ErrorMsg;
	} else {
		$PortList{$Port}  = $ErrorMsg;
	}

	$FreshPorts::CommitterOptIn::Errors .= $ErrorMsg . "\n\n" .
        "===================================================\n";
}

sub RecordCommitMessageID {
	$FreshPorts::CommitterOptIn::CommitMessageID .= shift;
}

sub RecordCommitMessageSubject {
	$FreshPorts::CommitterOptIn::CommitMessageSubject .= shift;
}

sub CommitterHasOptedIn($;$) {
	my $committer	= shift;
	my $dbh			= shift;

	my $OptedIn = 0;
	my $myrow;

	my $sql = "select committer
	             from committer_notify
	            where lower(committer) = lower('$committer')";
	my $sth = $dbh->prepare($sql);
	if (!$sth->execute())  {
		FreshPorts::Utilities::ReportError('warning', "Could not execute sql: $sql", 1);
	}

	# if we fetch a row, then the committer has opted in.
	if ($myrow = $sth->fetchrow_hashref()) {
		$OptedIn = 1;
	}

	return $OptedIn;
}

sub NotifyCommitter {
	my $committer	= shift;
	my $dbh			= shift;

	$Text::Wrap::columns = 72;

	my $Body = "This message was generated by the FreshPorts Daemon.

You recently made this commit, which FreshPorts FreshPorts had trouble 
processing:

MessageID: $FreshPorts::CommitterOptIn::CommitMessageID
Subject  : $FreshPorts::CommitterOptIn::CommitMessageSubject

The following is a list of the ports which had errors:

";

	while (my ($Port, $Error) = each %PortList) {
		$Body .= $FreshPorts::Config::FreshPortsURL . $Port . "/\n";
	}

	$Body .= "\n\nThe exact errors appear below.\n\n";

	while (my ($Port, $Error) = each %PortList) {
		$Body .= $Port . ":\n\n" . Text::Wrap::wrap('', '', $Error) . "\n";
	}

	if ($FreshPorts::Config::CommitterNotify) {
		$Body .= "

You are receiving this message as you are a FreeBSD
committer who has opted into this service.  Please
see http://www.FreshPorts.org/committer-opt-in.php
for more information.
";
	}

	$Body .= "
-- 
FreshPorts Daemon
";

	my $From         = 'FreshPorts Sanity Daemon <FreshPorts@FreshPorts.org>'; 
	my $To           = $FreshPorts::Config::SystemOwnerEmail;
	my $CC           = '';
	my $Subject      = 'FreshPorts sanity checking';

	my $Hostname     = `hostname`;

	# we must cut off the trailing newlines or the headers will not be altogether
	chomp $Hostname;

	my $ExtraHeaders = 'Auto-Submitted: auto-generated'           . "\n" .
					   "X-FreshPorts-Sanity: error\n" .
	                   "X-FreshPorts-Hostname: $Hostname\n" . 
	                   "X-FreshPorts-Database: $FreshPorts::Config::dbname";

	if ($FreshPorts::Config::CommitterNotify) {
		if ($FreshPorts::Config::CommitterNotify && CommitterHasOptedIn($committer, $dbh)) {
			$To = "$committer\@FreeBSD.org";
			$CC = $FreshPorts::Config::SystemOwnerEmail;
			FreshPorts::Utilities::ReportError('warning', "Committer $committer has been notified of errors: $FreshPorts::CommitterOptIn::Errors", 0);
		} else {
			$Body = "Committer $committer would have been notified of errors if they were opted in.\n\n$Body";
			FreshPorts::Utilities::ReportError('warning', "Committer $committer would have been notified of errors if they were opted in: $FreshPorts::CommitterOptIn::Errors", 0);
		}
	} else {
		$Body = "Committer notifications are disabled.  This commit was by $committer\n\n$Body";
		FreshPorts::Utilities::ReportError('warning', "Committer notifications are disabled.", 0);
	}

	FreshPorts::email::SendMail($From, $To, $CC, $Subject, $Body, $ExtraHeaders);
}

1;
