#
# $Id: committer_opt_in.pm,v 1.1.2.3 2002-11-24 17:14:57 dan Exp $
#
# Copyright (c) 2002 DVL Software
#

package FreshPorts::CommitterOptIn;

use email;

$FreshPorts::CommitterOptIn::Errors = '';

sub RecordErrorDetails {
	my $error = shift;

	$FreshPorts::CommitterOptIn::Errors .= $error;
}

sub CommitterHasOptedIn($;$) {
	my $committer	= shift;
	my $dbh			= shift;

	my $OptedIn = 0;

	my $sql = "select committer
              from committer_notify
             where lower(committer) = lower('$committer')";
	my $sth = $dbh->prepare($sql);
	if (!$sth->execute())  {
		FreshPorts::Utilities::ReportError('warning', "Could not execute sql: $sql", 1);
	}

	# if we fetch a row, then the committer has opted in.
	if ($myrow = $sth->fetchrow_hashref()) {
		$OptedIn = 1;
	}

	return $OptedIn;
}

sub NotifyCommitter {
	my $committer	= shift;
	my $dbh			= shift;

	# this would be where you would verify that a given committer was opt'd in

	if (CommitterHasOptedIn($committer, $dbh)) {

		$Body= "This message was generated by the FreshPorts Daemon.
A recent commit by you has produced the following
error during processing by FreshPorts:

$FreshPorts::CommitterOptIn::Errors

You are receiving this message as you are a FreeBSD
committer who has opted into this service.  Please
see http://www.FreshPorts.org/committer-opt-in.php
for more information.

--
hugs+kisses
FreshPorts Daemon
";

		FreshPorts::email::SendMail('FreshPorts Daemon <FreshPorts@FreshPorts.org>', "$committer\@FreeBSD.org", 'FreshPorts error', $Body);
		FreshPorts::Utilities::ReportError('warning', "Committer $committer has been notified of errors: $FreshPorts::CommitterOptIn::Errors", 0);
	} else {
		FreshPorts::Utilities::ReportError('warning', "Committer $committer would have been notified of errors if they were opted in: $FreshPorts::CommitterOptIn::Errors", 0);
	}
}

1;
