#!/bin/sh
#
# $Id: cvsup-local-tree,v 1.2 2007-10-17 18:27:25 dan Exp $
#
# Copyright (c) 2007 DVL Software Limited
#

# $DIR should be set externally
if [ "${DIR}X" = "X" ]
then
	echo DIR was not set
fi

cd ${DIR}

if [ ! -f config.sh ]
then
	echo config.sh was not found
	exit 1
fi

. config.sh

/usr/local/bin/cvsup -b ${PORTSDIR}/.. -h ${FREEBSDCVSUPHOST} ${DIR}/ports-supfile
cd ${PORTSDIR}
make fetchindex PORTSDIR=${PORTSDIR}
