#!/usr/bin/perl -w
#
# $Id: email.pl,v 1.8.2.6 2002-05-28 15:15:11 dan Exp $
#
# Copyright (c) 2001-2002 DVL Software
#

use strict;
use lib "$ENV{HOME}/scripts";

use port;
use database;
use DBI;
use config;

use Text::Wrap;

my $Debug = 0;
my $dirname='';
my @USERS;
my $sql;
my $sth;
my @row;
my $Bcc;
my $NumMsgs		= 0;
my $NumCommits	= 0;

my $FormatDate	= "%W, %b %e";
my $FormatTime	= "%H:%i";
my $WatchURL	= $FreshPorts::Config::FreshPortsURL . "watch.php";
sub SendWatchNoticePersonal($;$;$) {

	my $To            = shift;
	my $FrequencyLong = shift;
	my $Body          = shift;

	open(SENDMAIL, "|/usr/sbin/sendmail -oi -t")
					or die "Can't fork for sendmail: $!\n";

print SENDMAIL <<"EOF";
From: FreshPorts watch daemon <freshports-watch\@freshports.org>
To: $To
Subject: FreshPorts $FrequencyLong notification

This message was generated by the FreshPorts Watch Daemon and highlights
your selected ports which have changed since the last notification.  You
have chosen to receive these notices on a $FrequencyLong basis.

$Body

Please refer to $WatchURL for details.

Cheers and thanks for your support.

--

You are receiving this message as part of the service you joined at
http://freshports.org/ but if you no longer wish to receive such messages,
please go to http://freshports.org/customize.php and disable mailings.

If a problem occurs, please send details, including the email address in
question, to postmaster\@freshports.org.
EOF

	close(SENDMAIL)     or warn "sendmail didn't close nicely";
}


sub CompileWatchNotifyList($;$;$;$) {

	my $Frequency = shift;
	my $NewPorts  = shift;
	my $PortCount = shift;
	my $dbh = shift;
	my $sth;
	my $sql;

	#
	# get a list of ports to update
	#
	# the following line restricts mailouts to just me.
	#               and users.id                      = 2

	$sql = "select users.id, 
	               users.email, 
	               categories.name as category, 
	               element.name as port, 
	               to_char(commit_log.commit_date + INTERVAL '$FreshPorts::Config::TimeAdjust', 'DD Mon YYYY') as commit_date,
	               commit_log.description,
				   commit_log.committer
	          from commit_log, watch_notice, watch_list_element, 
	               watch_list, users, ports, categories, element, commit_log_ports
	         where commit_log.date_added           >= watch_notice.last_sent 
	           and commit_log.id                    = commit_log_ports.commit_log_id 
	           and watch_list_element.element_id    = ports.element_id
	           and watch_list_element.watch_list_id = watch_list.id 
	           and users.id                         = watch_list.user_id 
	           and users.watch_notice_id            = watch_notice.id
	           and watch_notice.frequency           = '$Frequency' 
	           and length(users.email)              > 0 
	           and users.emailbouncecount           = 0 
	           and ports.id                         = commit_log_ports.port_id
	           and ports.category_id                = categories.id
	           and ports.element_id                 = element.id 
	      order by users.id, categories.name, element.name, commit_log.commit_date";

#	print "sql is $sql\n";

	$sth = $dbh->prepare($sql);
	$sth->execute ||
			die "Could not execute SQL $sql ... maybe invalid?";

	my $LastID;
	my $Body;
	my $To;
	my $FrequencyLong;

	undef($LastID);

	if ($Frequency eq 'D') { $FrequencyLong = 'daily'};
	if ($Frequency eq 'W') { $FrequencyLong = 'weekly'};
	if ($Frequency eq 'F') { $FrequencyLong = 'fortnightly'};
	if ($Frequency eq 'M') { $FrequencyLong = 'monthly'};


	$Body .= "Port count: $PortCount\n";
	$Body .= " New ports: $NewPorts\n\n";

	while (@row=$sth->fetchrow_array) {
		print "now processing @row\n";
		$NumCommits++;

		# make sure that the first time through, we have a value
		if (!defined($LastID)) {
			$LastID = $row[0];
			$To     = $row[1];
		}

#		print "LastID = '$LastID' and id = '$row[0]'\n";
		if ($LastID != $row[0]) {
			$NumMsgs++;
			if ($Debug) {
				print "NOT SENDING EMAIL.. in DEBUG mode\n";
			} else {
				SendWatchNoticePersonal($To, $FrequencyLong, $Body);
			}
			print "To   = $To\n";
			print "Body = $Body\n";

			$Body   = '';
			$To     = $row[1];
			$LastID = $row[0];
		}

		# get the category and port
		$Body .= "$FreshPorts::Config::FreshPortsURL" . $row[2] . '/' . $row[3] . "/\n";

		# and wrap the description of the change.
		$Body .= wrap("     ", "     ", $row[5]) . "\n";
		$Body .=      "     $row[4] - $row[6]\n\n";
	}

	# if we got at least one, send out email
	if (defined($LastID)) {
		$NumMsgs++;
		if ($Debug) {
			print "NOT SENDING EMAIL.. in DEBUG mode\n";
		} else {
			SendWatchNoticePersonal($To, $FrequencyLong, $Body);
		}
	}
}

sub AddToLogs($;$;$;$) {
	my $Frequency	= shift;
	my $NumMsgs		= shift;
	my $NumCommits	= shift;
	my $dbh			= shift;

	my $sql;
	my @row;

	$sql = "select id from watch_notice where frequency = '$Frequency'";
	$sth = $dbh->prepare($sql);
	$sth->execute ||
		die "Could not execute SQL $sql ... maybe invalid?";

	@row=$sth->fetchrow_array;
	my $frequency_id = $row[0];

	$sql = "insert into watch_notice_log (frequency_id, msg_count, commit_count)
									values ('$frequency_id', $NumMsgs, $NumCommits)";
	$sth = $dbh->prepare($sql);
	$sth->execute ||
           die "Could not execute SQL $sql ... maybe invalid?";
}

sub SetWatchLastNoticeDate($;$;$) {

   my $Frequency = shift;
   my $dbh       = shift;
   my $time      = shift;

   $sql = "update watch_notice \
              set last_sent              = '$time' \
            where watch_notice.frequency = '$Frequency'";

print 'SQL = ' . $sql . "\n";

   $sth = $dbh->prepare($sql);

   $sth->execute ||
           die "Could not execute SQL $sql ... maybe invalid?";
}

#
# use current time as cutoff for next time we do this
#
my $time = `date "+%Y-%m-%d %H:%M:%S"`;

#
# if we don't chomp, we'll have a \n in the string
# which SQL won't like
#
chomp $time;

if ($Debug) {
	print "**********************************\n";
	print "running in debug mode.............\n";
	print "**********************************\n";
}



print "start  $time\n";

if (($#ARGV+1) == 1) {
	print "there is 1 argument\n";

	my $Frequency = $ARGV[0];

	if ($Frequency eq 'D' || $Frequency eq 'W' || $Frequency eq 'F' || $Frequency eq 'M') {

		my $dbh = FreshPorts::Database::GetDBHandle();
		if ($dbh->{Active}) {

			$sql = "select last_sent from watch_notice where frequency = '$Frequency'";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $last_sent = $row[0];
			$sth->finish();

			if (!defined($last_sent)) {
				if ($Frequency eq 'D') { $last_sent = `eval date -v-1d "+%Y_%m_%d"`};
				if ($Frequency eq 'W') { $last_sent = `eval date -v-7d "+%Y_%m_%d"`};
				if ($Frequency eq 'F') { $last_sent = `eval date -v-2w "+%Y_%m_%d"`};
				if ($Frequency eq 'M') { $last_sent = `eval date -v-1m "+%Y_%m_%d"`};
			}

			print "last_sent = $last_sent\n";

			$sql = "select Stats_PortCountNewInterval(now() - '$last_sent')";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $NewPorts = $row[0];
			$sth->finish();

			$sql = "select Stats_PortCount()";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $PortCount = $row[0];
			$sth->finish();

			print "NewPorts = $NewPorts, PortCount = $PortCount\n";

			CompileWatchNotifyList($Frequency, $NewPorts, $PortCount, $dbh);

			if (!$Debug) {
				SetWatchLastNoticeDate($Frequency, $dbh, $time);
				AddToLogs($Frequency, $NumMsgs, $NumCommits, $dbh);
			}

			$dbh->commit();
			$dbh->disconnect();

			print "message sent to users\n";
		}
	} else {
		print "$Frequency as mail out frequency is not known to me.\n";
	}
} else {
	print "please specify a frequency such as D, W, F, M\n";
}


print "start " . `date "+%Y-%m-%d %H:%M:%S"`;
