#!/usr/bin/perl -w
#
# $Id: report-new-ports.pl,v 1.1.2.9 2002-12-12 04:59:12 dan Exp $
#
# Copyright (c) 2001-2002 DVL Software
#

use strict;
use lib "$ENV{HOME}/scripts";

use port;
use database;
use DBI;
use config;
use report_constants;

use Text::Wrap;

my $Debug = 0;
my $dirname='';
my @USERS;
my $sql;
my $sth;
my @row;
my $Bcc;
my $NumMsgs		= 0;
my $NumCommits	= 0;
my $NumPorts    = 0;

my $FormatDate	= "%W, %b %e";
my $FormatTime	= "%H:%i";
my $WatchURL	= $FreshPorts::Config::FreshPortsURL . "watch.php";
my $AdjustURL	= $FreshPorts::Config::FreshPortsURL . "report-subscriptions.php";

my $ReportID	= $FreshPorts::ReportConstants::NewPorts;

sub SendWatchNoticePersonal($;$;$) {

	my $To            = shift;
	my $FrequencyLong = shift;
	my $Body          = shift;


	$Body = "HEADS UP: multiple watch lists:
see http://www.freshports.org/phorum/read.php?f=1&i=451&t=420
Your help is needed!

--

This is the new test report for notifications as found at
$AdjustURL.

FreshPorts runs on hardware and bandwidth supplied by BChosting. See
http://bchosting.com/track.php?refID=5665 for details.

This message was generated by the FreshPorts Watch Daemon and highlights
your selected ports which have changed since the last notification.  You
have chosen to receive these notices on a $FrequencyLong basis.

$Body

Cheers and thanks for your support.

-- 

You are receiving this message as part of the service you joined at
$FreshPorts::Config::FreshPortsURL but if you no longer wish to receive such messages,
please go to $AdjustURL.

If a problem occurs, please send details, including the email address in
question, to postmaster\@FreshPorts.org.
";

	FreshPorts::email::SendMail('FreshPorts Watch Daemon <FreshPorts-Watch@FreshPorts.org>', $To, "FreshPorts $FrequencyLong new ports", $Body, 'X-FreshPorts-NewPorts: ' . $FrequencyLong);
}


sub CompileWatchNotifyList($;$;$;$;$) {

	my $Frequency = shift;
	my $NewPorts  = shift;
	my $PortCount = shift;
	my $LastSent  = shift;
	my $dbh = shift;
	my $sth;
	my $sql;

	#
	# get a list of ports to update
	#
	# the following line restricts mailouts to just me.
	#               and users.id                      = 2

	$sql = "
  select users.id, 
         users.email, 
         categories.name as category, 
         element.name    as port, 
         to_char(ports.date_added + SystemTimeAdjust(), 'DD Mon YYYY') as date_added,
         ports.short_description
    from users, ports, categories, element, report_frequency, report_subscriptions
   where report_frequency.frequency        = '$Frequency' 
     and length(users.email)               > 0 
     and users.emailbouncecount            = 0 
     and ports.category_id                 = categories.id
     and ports.element_id                  = element.id 
     and users.id                          = report_subscriptions.user_id
     and report_subscriptions.report_id    = $ReportID
     and report_frequency.id               = report_subscriptions.report_frequency_id
     and ports.date_added                  > '$LastSent'
order by users.id, categories.name, element.name, date_added";

	if ($Debug)	{
		print "sql is $sql\n";
	}

	$sth = $dbh->prepare($sql);
	$sth->execute ||
			die "Could not execute SQL $sql ... maybe invalid?";

	my $LastID;
	my $Body;
	my $To;
	my $FrequencyLong;
	my $Interval;
	my $CommitLogID = 0;

	undef($LastID);

	if ($Frequency eq 'D') {
		$FrequencyLong = 'daily';
		$Interval      = 'today';
	}
	if ($Frequency eq 'W') {
		$FrequencyLong = 'weekly';
		$Interval      = 'week';
	}
	if ($Frequency eq 'F') {
		$FrequencyLong = 'fortnightly';
		$Interval      = 'fortnight';
	}
	if ($Frequency eq 'M') {
		$FrequencyLong = 'monthly';
		$Interval      = 'month';
	}

	while (@row=$sth->fetchrow_array) {
		print "now processing @row\n";
		$NumPorts++;
#		if ($CommitLogID ne $row[7]) {
#			$NumCommits++;
#			$CommitLogID = $row[7];
#		}

		# make sure that the first time through, we have a value
		if (!defined($LastID)) {
			$LastID = $row[0];
			$To     = $row[1];
		}

#		print "LastID = '$LastID' and id = '$row[0]'\n";
		if ($LastID != $row[0]) {
			$NumMsgs++;
			if ($Debug) {
				print "NOT SENDING EMAIL.. in DEBUG mode\n";
			} else {
				SendWatchNoticePersonal($To, $FrequencyLong, $Body);
			}
			print "To   = $To\n";
			print "Body = $Body\n";

			$Body   = '';
			$Body .= "Port count: $PortCount http://www.freshports.org/categories.php\n";
			$Body .= " New ports: $NewPorts  http://www.freshports.org/ports-new.php?interval=$Interval\n\n";
			$To     = $row[1];
			$LastID = $row[0];
		}

		# get the category and port
		$Body .= "$FreshPorts::Config::FreshPortsURL" . $row[2] . '/' . $row[3] . "/\n";

		# and wrap the description of the change.
		$Body .= wrap("     ", "     ", $row[5]);
		$Body .=      "     $row[4]\n\n";
	}

	# if we got at least one, send out email
	if (defined($LastID)) {
		$NumMsgs++;
		if ($Debug) {
			print "NOT SENDING EMAIL.. in DEBUG mode\n";
		} else {
			SendWatchNoticePersonal($To, $FrequencyLong, $Body);
		}
	}
}

sub AddToLogs($;$;$;$;$;$) {
	my $report_id   = shift;
	my $Frequency	= shift;
	my $NumMsgs		= shift;
	my $NumCommits	= shift;
	my $NumPorts	= shift;
	my $dbh			= shift;

	my $sql;
	my @row;

	$sql = "select id from report_frequency where frequency = '$Frequency'";
	$sth = $dbh->prepare($sql);
	$sth->execute ||
		die "Could not execute SQL $sql ... maybe invalid?";

	@row=$sth->fetchrow_array;
	my $frequency_id = $row[0];

	$sql = "insert into report_log (report_id, frequency_id, email_count, commit_count, port_count)
									values ($report_id, '$frequency_id', $NumMsgs, $NumCommits, $NumPorts)";
	$sth = $dbh->prepare($sql);
	$sth->execute ||
           die "Could not execute SQL $sql ... maybe invalid?";
}

#
# use current time as cutoff for next time we do this
#
my $time = `date "+%Y-%m-%d %H:%M:%S"`;

#
# if we don't chomp, we'll have a \n in the string
# which SQL won't like
#
chomp $time;

if ($Debug) {
	print "**********************************\n";
	print "running in debug mode.............\n";
	print "**********************************\n";
}



print "start  $time\n";

if (($#ARGV+1) == 1) {
	print "there is 1 argument\n";

	my $Frequency = $ARGV[0];

	if ($Frequency eq 'D' || $Frequency eq 'W' || $Frequency eq 'F' || $Frequency eq 'M') {

		my $dbh = FreshPorts::Database::GetDBHandle();
		if ($dbh->{Active}) {

			$sql = "select last_sent 
			          from report_log_latest
			         where frequency = '$Frequency'
			           and report_id = $ReportID";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $last_sent = $row[0];
			$sth->finish();

			if (!defined($last_sent)) {
				if ($Frequency eq 'D') { $last_sent = `eval date -v-1d "+%Y/%m/%d"`};
				if ($Frequency eq 'W') { $last_sent = `eval date -v-7d "+%Y/%m/%d"`};
				if ($Frequency eq 'F') { $last_sent = `eval date -v-2w "+%Y/%m/%d"`};
				if ($Frequency eq 'M') { $last_sent = `eval date -v-1m "+%Y/%m/%d"`};

				chomp $last_sent;
			}

			print "last_sent = $last_sent\n";

			$sql = "select Stats_PortCountNewInterval(now() - '$last_sent')";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $NewPorts = $row[0];
			$sth->finish();

			$sql = "select Stats_PortCount()";
			$sth = $dbh->prepare($sql);
			$sth->execute ||
					die "Could not execute SQL $sql ... maybe invalid";

			@row=$sth->fetchrow_array;
			my $PortCount = $row[0];
			$sth->finish();

			print "NewPorts = $NewPorts, PortCount = $PortCount\n";

			CompileWatchNotifyList($Frequency, $NewPorts, $PortCount, $last_sent, $dbh);

			if (!$Debug) {
				AddToLogs($ReportID, $Frequency, $NumMsgs, $NumCommits, $NumPorts, $dbh);
			}

			$dbh->commit();
			$dbh->disconnect();

			print "message sent to users\n";
		}
	} else {
		print "$Frequency as mail out frequency is not known to me.\n";
	}
} else {
	print "please specify a frequency such as D, W, F, M\n";
}


print "finish " . `date "+%Y-%m-%d %H:%M:%S"`;
