#!/bin/sh
if [ ! -f config.sh ]
then
	echo "config.sh not found..."
	exit 1
fi

. config.sh


touch ${SCRIPTDIR}/OFFLINE
sudo svc -d /var/service/freshports
sudo svc -d /var/service/fp-listen

sudo /usr/local/etc/rc.d/postgresql restart

sudo svc -u /var/service/fp-listen
sudo svc -u /var/service/freshports
rm ${SCRIPTDIR}/OFFLINE
