#
#
# $Id: utilities.pm,v 1.24 2012-07-15 21:39:07 dan Exp $
#
# Copyright (c) 2001-2006 DVL Software
#

package FreshPorts::Utilities;

require config;
require Sys::Syslog;

require	email;
require Text::Wrap;

# =================================

sub ReadFile($) {

	my $file = shift;
	my $content;

	open F,$file;
	if (stat F) {
		$content = "";
		while(<F>){
			$content .= $_;
		}
	} else {
		FreshPorts::Utilities::ReportError('warning', "cannot open file $file", 1);
	}

	close F;

	return $content;
}

sub FetchFile($;$;$;$;) {
	#
	# fetch a file
	# into the given path
	# returns 1 if fetched.
	# zero otherwise.
	#
	my $DESTDIR		= shift;
	my $SRCDIR		= shift;
	my $FILE		= shift;
	my $REVISION	= shift;

	return FetchFileURL($FreshPorts::Config::SVN_Repository, $DESTDIR, $SRCDIR, $FILE, $REVISION, "''");
}

sub FetchFileURL($;$;$;$;$;$) {
	#
	# fetch a file
	# into the given path
	# returns 1 if fetched.
	# zero otherwise.
	#
	my $URL			= shift;
	my $DESTDIR		= shift;
	my $SRCDIR		= shift;
	my $FILE		= shift;
	my $REVISION	= shift;
	my $SUFFIX      = shift;
	
	my $REPO        = 'ports';
	
	$SRCDIR =~s!^/?ports/!!;

#	print "FetchFileURL '$URL' '$DESTDIR' '$SRCDIR' '$FILE' '$REVISION' '$SUFFIX'\n";

	my $result = 0;

	my $FetchAttempts = $FreshPorts::Config::Fetch_Retry_Limit;

	while ($FetchAttempts) {
		my $command = "sh $FreshPorts::Config::scriptpath/fetch-svn-file.sh $URL $REPO $DESTDIR $SRCDIR $FILE $REVISION $SUFFIX 2>&1";
		print "about to fetch = '$command'\n";
		my $FetchResults = `$command`;
		my $code = $?;
		print "fetch result = $code\n";
		if (($code >> 8)) {
			#
			# This might be a nice place to retry a fetch, or send an email
			#
			print "that fetch failed.  What do to?\n";
			print "\n\n" . $FetchResults . "\n\n";

			# and we're outta here
			# fetch failed
			# sleep, then try again

			Sys::Syslog::syslog('warning', "sleeping after fetch failed for ($DESTDIR $SRCDIR $FILE)");
			print "fetch failed, sleeping...\n";
			sleep $FreshPorts::Config::Fetch_Sleep_Time;
			$FetchAttempts--;

		} else {
			# fetch worked
			last;
		}
    }

	#
	# if we succeeded in our fetch..
	if ($FetchAttempts) {
		$result = 1;
	}

	return $result;
}

#
# make sure we init only once...
#
$FreshPorts::Utilities::syslog_init = 0;

sub InitSyslog() {
	if (!$FreshPorts::Utilities::syslog_init) {
		Sys::Syslog::setlogsock('unix');
		Sys::Syslog::openlog('FreshPorts', 'cons, pid', 'user');
		$FreshPorts::Utilities::syslog_init = 1;
	}
}


sub ReportError($;$;$) {
	my $level	= shift;
	my $message	= shift;
	my $die		= shift;

	my $email   = $die;

	_ReportErrorHelper($level, $message, $email, $die, 1);
}

sub ReportErrorEmail($;$;$;$) {
	my $level	= shift;
	my $message	= shift;
	my $email   = shift;
	my $die		= shift;

	_ReportErrorHelper($level, $message, $email, $die, 1);
}

sub ReportErrorEmailNoPrint($;$;$;$) {
	my $level	= shift;
	my $message	= shift;
	my $email   = shift;
	my $die		= shift;

	_ReportErrorHelper($level, $message, $email, $die, 0);
}

sub _ReportErrorHelper($;$;$;$;$) {
	my $level	= shift;
	my $message	= shift;
	my $email   = shift;
	my $die		= shift;
	my $print   = shift;

	my $suffix = $FreshPorts::Config::scriptpath;

	Sys::Syslog::syslog($level, $message . " ($suffix)");
	if ($print) {
		print $message . "\n";
	}

	if ($email) {
		SendEmailNotice($FreshPorts::Config::SystemOwnerEmail, $message);
	}

	if ($die) {
		die $message . "\n";
	}
}

sub SendEmailNotice($;$) {
	my $To	 = shift;
	my $Body = shift;

	my $From         = 'FreshPorts Daemon <FreshPorts@FreshPorts.org>';
	my $CC           = '';
	my $Subject      = 'FreshPorts error on ' . `hostname`;
	my $ExtraHeaders = '';
	$ExtraHeaders   .= 'Auto-Submitted: auto-generated'      . "\n";
	$ExtraHeaders   .= 'Precedence: bulk'                    . "\n";
	$ExtraHeaders   .= 'X-FreshPorts-Error: oops'            . "\n";

	$Text::Wrap::columns = 72;

	$Body = "This message was generated by the FreshPorts Daemon.

The database is $FreshPorts::Config::dbname
at $FreshPorts::Config::FreshPortsURL

" . Text::Wrap::wrap('', '', $Body) . "

--
hugs+kisses
FreshPorts Daemon
";

	FreshPorts::email::SendMail($From, $To, $CC, $Subject, $Body, $ExtraHeaders);
}

sub trim {
	my $s = shift;

	chomp($s);      # get rid of \n
	$s =~ s/^\s+//; # remove leading spaces
	$s =~ s/\s+$//; # remove trailing spaces

	return $s;
}

sub trim_multiple_to_single {
	my $s = shift;
	
	$s =~ s/\s+/ /g; # Convert multiple blank spaces to single spaces

	return $s;
}

sub TmpFileName($) {
	my $Tag = shift;

	($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime(time);

	$RealMonth = $mon  + 1;
	$RealYear  = $year + 1900;

	my $TmpFileName = '/tmp/FreshPorts.';
	if ($Tag ne '') {
		$TmpFileName .= "$Tag.";
	}
	$TmpFileName .= "$RealYear.$RealMonth.$mday.$hour.$min.$sec.$$";

	return $TmpFileName;
}


sub NULLIfEmpty {
	my $dbh   = shift;
	my $value = shift;

	my $result = undef;

	if (!defined($value) || $value eq '') {
		$result = 'NULL';
	} else {
		$result = $dbh->quote($value);
	}

	return $result;
}




FreshPorts::Utilities::InitSyslog();

1;
