# $Id: utilities.pm,v 1.11.2.12 2003-04-23 22:01:44 dan Exp $
#
#
# Copyright (c) 2001 DVL Software
#
package FreshPorts::Utilities;

require config;
require Sys::Syslog;

require	email;

# =================================

sub ReadFile($) {

	my $file = shift;
	my $content;

	open F,$file;
	if (stat F) {
		$content = "";
		while(<F>){
			$content .= $_;
		}
	} else {
		FreshPorts::Utilities::ReportError('warning', "cannot open file $file", 1);
	}

	close F;

	return $content;
}

sub FetchFile($;$;$;$) {
	#
	# fetch a file
	# into the given path
	# returns 1 if fetched.
	# zero otherwise.
	#
	my $DESTDIR		= shift;
	my $SRCDIR		= shift;
	my $FILE			= shift;
	my $REVISION	= shift;

	print "FetchFile $DESTDIR $SRCDIR $FILE $REVISION\n";

	my $result  = 0;

	my $FetchAttempts = 5;

	while ($FetchAttempts) {
		my $command = "sh $FreshPorts::Config::scriptpath/fetch-cvs-file.sh $DESTDIR $SRCDIR $FILE $REVISION 2>&1";
		print "fetch command = '$command'";
		my $FetchResults = `$command`;
		$result = $?;
		print "fetch result = $result\n";
		if (($result >> 8)) {
			#
			# This might be a nice place to retry a fetch, or send an email
			#
			print "that fetch failed.  What do to?\n";
			print "\n\n" . $FetchResults . "\n\n";

			# and we're outta here
			# fetch failed
			# sleep, then try again

			Sys::Syslog::syslog('warning', "sleeping after fetch failed for ($DESTDIR $SRCDIR $FILE)");
			print "fetch failed, sleeping...\n";
			sleep 10;
			$FetchAttempts--;

		} else {
			# fetch worked
			last;
		}
    }

	#
	# if we succeeded in our fetch..
	if ($FetchAttempts) {
		$result = 1;
	}

	return $result;
}

#
# make sure we init only once...
#
$FreshPorts::Utilities::syslog_init = 0;

sub InitSyslog() {
	if (!$FreshPorts::Utilities::syslog_init) {
		Sys::Syslog::setlogsock('unix');
		Sys::Syslog::openlog('FreshPorts', 'cons, pid', 'user');
		$FreshPorts::Utilities::syslog_init = 1;
	}
}


sub ReportError($;$;$) {
	my $level	= shift;
	my $message	= shift;
	my $die		= shift;

	my $email   = $die;

	_ReportErrorHelper($level, $message, $email, $die);
}

sub ReportErrorEmail($;$;$;$) {
	my $level	= shift;
	my $message	= shift;
	my $email   = shift;
	my $die		= shift;

	_ReportErrorHelper($level, $message, $email, $die);
}

sub _ReportErrorHelper($;$;$;$) {
	my $level	= shift;
	my $message	= shift;
	my $email   = shift;
	my $die		= shift;

	my $suffix = $FreshPorts::Config::scriptpath;

	Sys::Syslog::syslog($level, $message . " ($suffix)");
	print $message . "\n";

	if ($email) {
		SendEmailNotice('dan@langille.org', $message);
	}

	if ($die) {
		die $message . "\n";
	}
}

sub SendEmailNotice($;$) {
	my $To	= shift;
	my $Body	= shift;

	my $hostname = `hostname`;

	$Body = "This message was generated by the FreshPorts Daemon.

The database is $FreshPorts::Config::dbname
at $FreshPorts::Config::FreshPortsURL

$Body

--
hugs+kisses
FreshPorts Daemon
";

	FreshPorts::email::SendMail('FreshPorts Daemon <FreshPorts@FreshPorts.org>', $To, 'FreshPorts error on ' . $hostname, $Body, 'X-FreshPorts-Error: oops');
}

sub trim {
	my $s = shift;

	chomp($s);      # get rid of \n
	$s =~ s/^\s+//; # remove leading spaces
	$s =~ s/\s+$//; # remove trailing spaces

	return $s;
}

sub trim_multiple_to_single {
	my $s = shift;
	
	$s =~ s/\s+/ /g; # Convert multiple blank spaces to single spaces

	return $s;
}

sub TmpFileName($) {
	my $Tag = shift;

	($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime(time);

	$RealMonth = $mon  + 1;
	$RealYear  = $year + 1900;

	my $TmpFileName = '/tmp/FreshPorts.';
	if ($Tag ne '') {
		$TmpFileName .= "$Tag.";
	}
	$TmpFileName .= "$RealYear.$RealMonth.$mday.$hour.$min.$sec.$$";

	return $TmpFileName;
}

1;
