#!/usr/bin/perl

package	ports;
require	Exporter;

#use strict;

@ISA		= qw(Exporter);
@EXPORT	= qw(PortUpdate ExtractCategoryFromDirectory GetDescrAndHomePage ReadFile PackageExists RefreshPort SendWatchNotice);

sub SendWatchNotice($) {

  my $Bcc = shift;

   open(SENDMAIL, "|/usr/sbin/sendmail -oi -t")
                    or die "Can't fork for sendmail: $!\n";

print SENDMAIL <<"EOF";
From: FreshPorts watch daemon <freshports-watch\@freshports.org>
To: freshports-watch\@freshports.org
Bcc: $Bcc
Subject: FreshPorts watch list notification

This message was generated by the FreshPorts Watch Daemon.
Something on your watch list has changed.  But I'm too
confused to tell you exactly what.  Please refer to
http://freshports.org/watch.php3 for details.

Cheers and thanks for your support.

--

You are receiving this message as part of the service
you joined at http://freshports.org/ but if you no longer
wish to recieve such messages, please go to
http://freshports.org/customize.php3 and disable mailings.

If a problem occurs, please send details, including the email
address in question, to postmaster\@freshports.org
EOF

   close(SENDMAIL)     or warn "sendmail didn't close nicely";

}

# =================================    
sub ExtractCategoryFromDirectory($) {

   my $dir = shift;

print "directory = $dir\n";

   # split the dir into separate elements
   my @fields = split(/\//, $dir);

   #grab the last one.
   my $category = $fields[$#fields];

print "category = $category\n";

   # who's your daddy?
   return $category
}
   

# =================================
sub PackageExists($) {

   my $package = shift;
   my $exists  = "N";

   open F,"/usr/local/etc/freshports/packages.exists";

LINE:
   while(<F>){
#      if(/$package/) {
       if(index($_, $package) != -1 ) {
         $exists = "Y";
         last LINE;
      }
   }
   close F;
                                                                
   return $exists;                                              
}  



# =================================
sub ReadFile($) {

   my $file = shift;
   my $content;

   open F,$file;

   $content = "";
   while(<F>){
      $content .= $_;
   }

   close F;

   return $content;
}


# =================================
sub GetDescrAndHomePage($) {

   my $file = shift;
   my $url;
   my $DESCR;

   open F,$file;

   $DESCR = "";
   while(<F>){
      $DESCR .= $_;
      if(/WWW:(.*)/) {

#print "found a home page of $url\n";

         $url = $1;
         $url =~  s/^\s+//g;
      }
   }

   close F;                              
                                                                
   my @result = ($DESCR, $url);                                    
                                                                
   return @result;                                              
}


# =================================
sub GetCategoryFromCategories($) {
   my $categories = shift;
   my $category;

   ($category) = split(/ /s, $categories);

   return $category;
}


# =================================

#sub GetPortCategory($category, $dbh) {
sub GetPortCategory($;$) {
   my $category = shift;
   my $dbh = shift;

   my $sql = "select id from categories where name = '" . $category . "'";

   print "\n",$sql, "\n";

   my $sth = $dbh->prepare($sql);

   $sth->execute ||
        die "Could not execute SQL statement ... maybe invalid?";


   my @row=$sth->fetchrow_array;

   print "\nGetPortCategory = $sql which gives ", $row[0], "\n";

   return $row[0];
}

sub PortUpdate($;$;$;$;$;$;$;$;$;$;$;$;$;$;$;$;$) {
#PortUpdate ($name, $portname, $category, $descrfile, $categories, $portversion, 
#          $commentfile, $maintainer, $extractsuffix, $mastersites, $builddepends,
#    $rundepends, $shortdescription, $longdescription, $homepage, $packageexists, $dbh);

   my $name             = shift;
   my $portname         = shift;
   my $category         = shift;
   my $descrfile        = shift;
   my $categories       = shift;
   my $portversion      = shift;
   my $commentfile      = shift;
   my $maintainer       = shift;
   my $extractsuffix    = shift;
   my $mastersites      = shift;
   my $builddepends     = shift;
   my $rundepends       = shift;
   my $shortdescription = shift;
   my $longdescription  = shift;
   my $homepage         = shift;
   my $packageexists    = shift;
   my $dbh              = shift;


if ($name ne $portname) {
   print "*************** port ('$name') differs from portname('$portname')\n";
}

print " 0 $name\n";
print " 1 $portname\n";
print " a $category\n";
print " 2 $descrfile\n";
print " 3 $categories\n";
print " 4 $portversion\n";
print " 5 $commentfile\n";
print " 6 $maintainer\n";
print " 7 $extractsuffix\n";
print " 8 $mastersites\n";
print " 9 $builddepends\n";
print "10 $rundepends\n";
print "11 $shortdescription\n";
print "12 $longdescription\n";
print "13 ";
if (defined($homepage)) {
   print "$homepage";                 # this may be an unitialized value
}
print "\n";
print "14 $packageexists\n";

# this asks for user input
#<STDIN>;

#return;

   my $categoryid = GetPortCategory($category, $dbh);
   if (!$categoryid) {
      print "ERROR *** could not find category for $category\n";
      exit;
   }

   # update the port, creating it if necessary

   my $sql = "select id from ports where name = '$name' and primary_category_id = $categoryid";
   print "sql = ", $sql, "\n";
   my $sth = $dbh->prepare($sql);

   $sth->execute ||
      die "Could not execute SQL statement ... maybe invalid?";

   my @row=$sth->fetchrow_array;

   if (@row) {
      print "something found\n";
   } else {
      print "nothing found\n";
   }

   # Get the short description (and escape them)
   # Get the long description (and escape them)
   # get homepage
   # get package exists

   print "port ID found = ", $row[0], "\n";
   if (!@row) {
      # no such port.  create it.
      $sql = "insert into ports (name,                                                                    \
              primary_category_id, system, version, date_created,                                         \
              short_description, long_description, maintainer, categories,                                \
              date_last_refreshed, needs_refresh, homepage, master_sites, extract_suffix, package_exists, \
              status, depends_run, depends_build) values (";

      $sql .= "'$name', $categoryid ,                                                     \
              'FreeBSD', '$portversion', current_timestamp, '$shortdescription',          \ 
              '$longdescription', '$maintainer', '$categories', current_timestamp, 'N', ";

      if (defined($homepage)) {
         $sql .= "'$homepage', ";
      } else {
         $sql .= "NULL, ";
      }

      $sql .= "'$mastersites', '$extractsuffix', '$packageexists', 'A',       \
               '$rundepends', '$builddepends')";

      print "$sql\n";

      $sth = $dbh->prepare($sql);

      $sth->execute ||
         die "Could not insert statement ... maybe invalid?";
   } else {
      # update the time on the port
      $sql = "update ports set \ 
              version = '$portversion', short_description = \
              '$shortdescription', long_description = '$longdescription', maintainer = \
              '$maintainer', categories = '$categories', date_last_refreshed = \
              current_timestamp, ";

      if (defined($homepage)) {
         $sql .= "homepage = '$homepage',";
      } else {
         $sql .= "homepage = NULL,";
      }

      $sql .= " master_sites = '$mastersites', \
                extract_suffix = '$extractsuffix', package_exists = '$packageexists', \
                needs_refresh = 'N', depends_run = '$rundepends', depends_build = '$builddepends' \
                where id = $row[0]";

      print "$sql\n";

      $sth = $dbh->prepare($sql);

      $sth->execute ||
         die "Could not execute update statement ... maybe invalid?";
   }
 }


sub RefreshPortNoChecking($;$;$;$;$) {

   my $DirectoryOfMakeFile = shift;
   my $Category            = shift;
   my $Port                = shift;
   my $NameOfMakefile      = shift;
   my $dbh                 = shift;

   #
   # if we don't change the working dir, stuff like descrpath will not
   # contain /usr/ports/...etc.  It will look more like this:
   #     /usr/home/dan/walkports/pkg/DESCR
   # That's because DESCR is define as .{CURDIR}/pkg/DESCR etc more or less
   #

   my $makecommand = "make -V PORTNAME -V PKGNAME -V DESCR -V CATEGORIES -V PORTVERSION " .
         "-V COMMENT -V MAINTAINER -V EXTRACT_SUFX -V MASTER_SITES " .
         "-V BUILD_DEPENDS -V RUN_DEPENDS -f $DirectoryOfMakeFile/$NameOfMakefile";

   print "makecommand = $makecommand\n";
   chdir "$DirectoryOfMakeFile";

   (my $portname, my $packagename, my $descrpath, my $categories, my $portversion, my $commentfile,
    my $maintainer, my $extractsuffix, my $mastersites, my $builddepends,
    my $rundepends) = split(/\n/s, `$makecommand`);

   print " 0 $Port\n";
   print " 1 $portname\n";
   print " a $Category\n";
   print " 2 $packagename\n";
   print " 3 $descrpath\n";
   print " 4 $categories\n";
   print " 5 $portversion\n";
   print " 6 $commentfile\n";
   print " 7 $maintainer\n";
   print " 8 $extractsuffix\n";
   print " 9 $mastersites\n";
   print "10 $builddepends\n";
   print "11 $rundepends\n";

   (my $longdescription, my $homepage) = GetDescrAndHomePage($descrpath);
   my $shortdescription = ReadFile($commentfile);

   my $packageexists = PackageExists($packagename . ".tgz");

   # because we are adding in \ before the quotes,
   # we need to quote the \'s first.

   #  these bits might have \'s.
   $longdescription  =~ s/\\/\\\\/g;
   $shortdescription =~ s/\\/\\\\/g;

   #  these bits might have quotes.
   $longdescription  =~ s/\'/\\'/g;
   $shortdescription =~ s/\'/\\'/g;

   print "12 $shortdescription\n";
   print "13 $longdescription\n";
   print "14 ";
   if (defined($homepage)) {
      print "$homepage";
   }
   print "\n";
   print "15 $packageexists\n";

   print "\n ---------------------------------------- \n";

#   PortUpdate ($Port, $portname, $Category, $descrpath, $categories, $portversion,
#      $commentfile, $maintainer, $extractsuffix, $mastersites, $builddepends,
#      $rundepends, $shortdescription, $longdescription, $homepage, $packageexists, $dbh);
}

sub RefreshPort($;$;$) {

   my $dirname = shift;
   my $port    = shift;
   my $dbh     = shift;

   print "... now checking $dirname/$port .... ";
   if (-d "$dirname/$port") {
      #
      # at one time, $IGNOREDPORTS contained . and .. but that caused
      # problems with port names which contained a '.'
      # hence, this solution.  Also, pkg causes similar problems
      # as the port pkg_remove would match that
      # my $IGNOREDPORTS = "pkg|CVS|apache13-php3-fp-modssl|Makefile";
      if ($port eq "." || $port eq ".." || $port eq "pkg" || $port eq "CVS" || $port eq "Makefile") {
         print "port is in the IGNORE list... skipping\n";
      } else {
         if (!-e "$dirname/$port/Makefile") {
            print " ...makefile does not exist (port must be in Attic)\n";
         } else {
            print "...now looking at $dirname/$port/Makefile\n";

            my $category = ExtractCategoryFromDirectory($dirname);

            RefreshPortNoChecking("$dirname/$port", $category, $port, 'Makefile', $dbh);

         }  # else yes, the Makefile does exist.
      }
   } else {
      print "directory does not exist... skipping\n";
   }
}
